
/**
 * HTTP CODES
 */
const SUCCESSFUL_REQUEST = 200;
const BAD_REQUEST = 400;
const INVALID_OR_MISSING_TOKEN = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const METHOD_NOT_ALLOWED = 405;
const SERVER_ERROR = 500;


/**
 * BRAINFES CONSTANTS
 */

const OPERATION_OK = "OPERATION SUCCESFULL";
const OPERATION_FAILED = "OPERATION FAILED"; 
const DATA_NOT_FOUND = "DATA NOT FOUND";
const DATA_CREATED = "DATA CREATED";
const DATA_DELETED = "DATA DELETED";
const DATA_NOT_DELETE = "DATA NOT DELETE";
const DATA_UPDATED = "DATA UPDATED";
const DATA_NOT_UPDATED = "DATA NOT UPDATED";
const DATABASE_CONNECTION = "DATABASE CONNECTION OK";
const INVALID_LOGIN = "INVALID LOGIN";
const MONGO_ERROR_DUPLICATED = "DUPLICATED VALUE";
const DATA_NOT_CREATED = "DATA NOT CREATED";
const DUPLICATED_DATA = "DUPLICATED DATA";
const DATA_DISABLED = "DATA DISABLED";
  

module.exports = {
    SUCCESSFUL_REQUEST,
    BAD_REQUEST,
    INVALID_OR_MISSING_TOKEN,
    FORBIDDEN,
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    SERVER_ERROR,
    OPERATION_OK,
    OPERATION_FAILED,
    DATA_NOT_FOUND,
    DATA_CREATED,
    DATA_DELETED,
    DATA_UPDATED,
    DATABASE_CONNECTION,
    INVALID_LOGIN,
    MONGO_ERROR_DUPLICATED,
    DATA_NOT_CREATED,
    DATA_NOT_UPDATED,
    DUPLICATED_DATA,
    DATA_DISABLED,
    DATA_NOT_DELETE

}
